name: Seed Database and Push Changes

on:
  schedule:
    - cron: '30 11 * * *'  # Runs at 11:30 UTC daily
  workflow_dispatch:

permissions:
    contents: write

jobs:
  seed_and_push:

    runs-on: ubuntu-latest

    env:
      GIT_PROVIDER: ${{ vars.GIT_PROVIDER }}
      GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build and start Next.js app in the background
        env:
          GIT_PROVIDER: ${{ env.GIT_PROVIDER }}
          GITCODE_TOKEN: ${{ env.GITCODE_TOKEN }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          npm run build
          npm run start &

      - name: Wait for the server to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:3000/api/repos && break
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Send request to /api/seed
        run: |
          curl http://localhost:3000/api/seed

      - name: Check for changes in SQLite DB
        run: |
          git config --global user.name "huqi"
          git config --global user.email "huqi1024@gmail.com"
          git add .
          git commit -m "feat: new entities added" || echo "No changes to commit"
          git push origin main